export * from './bøying.command';
export * from './detect-language.command';
export * from './islandsk.command';
export * from './notion';
export * from './ordbok.command';
export * from './random.command';
export * from './quote.command';
export * from './tilfeldig-ord.command';
export * from './translate';
