name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - Procfile
      - template.env
      - norsk-bott-icon.png
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable

      - name: Check formatting
        run: yarn format:check

      - name: Lint
        run: yarn lint:check
        if: ${{ success() || failure() }}
