name: Test Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/workflows/build-image.yml
      - .github/workflows/lint.yml
      - Procfile
      - .prettierrc
      - renovate.json
      - template.env
      - norsk-bott-icon.png
      - eslint.config.mjs
      - test/
      - .vscode/
  merge_group:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build
